// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAF8OyjnnbtwkxCRmTqNSqH1mu5UMDxw8',
    appId: '1:349848231876:web:be906c38dfa3d965b24e91',
    messagingSenderId: '349848231876',
    projectId: 'ilimi-hackaton',
    authDomain: 'ilimi-hackaton.firebaseapp.com',
    storageBucket: 'ilimi-hackaton.firebasestorage.app',
    measurementId: 'G-W74H9KLXET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0jW_exEfLsJSv97HzcnW6CZTDN4A04kE',
    appId: '1:349848231876:android:31d7c9d2e68cf5c9b24e91',
    messagingSenderId: '349848231876',
    projectId: 'ilimi-hackaton',
    storageBucket: 'ilimi-hackaton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqcKrrpeQmtxNtJCSMJNYDkQbXzlzXoM',
    appId: '1:349848231876:ios:fbad333349cbc5e3b24e91',
    messagingSenderId: '349848231876',
    projectId: 'ilimi-hackaton',
    storageBucket: 'ilimi-hackaton.firebasestorage.app',
    iosBundleId: 'com.example.ilimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqcKrrpeQmtxNtJCSMJNYDkQbXzlzXoM',
    appId: '1:349848231876:ios:fbad333349cbc5e3b24e91',
    messagingSenderId: '349848231876',
    projectId: 'ilimi-hackaton',
    storageBucket: 'ilimi-hackaton.firebasestorage.app',
    iosBundleId: 'com.example.ilimi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAF8OyjnnbtwkxCRmTqNSqH1mu5UMDxw8',
    appId: '1:349848231876:web:25f1b14305b3f843b24e91',
    messagingSenderId: '349848231876',
    projectId: 'ilimi-hackaton',
    authDomain: 'ilimi-hackaton.firebaseapp.com',
    storageBucket: 'ilimi-hackaton.firebasestorage.app',
    measurementId: 'G-PVRN6M0KKR',
  );

}