// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN96Sb18FoF7MjSLNZ2tF3yJeIt-7SS7s',
    appId: '1:167014119386:web:c1496ea0dcd1630afb72e3',
    messagingSenderId: '167014119386',
    projectId: 'ilimi-9f802',
    authDomain: 'ilimi-9f802.firebaseapp.com',
    storageBucket: 'ilimi-9f802.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEgYMLS2yaLpgSvrLlO_8ThsRCZfYHhY',
    appId: '1:167014119386:android:9d81c0d918dbc739fb72e3',
    messagingSenderId: '167014119386',
    projectId: 'ilimi-9f802',
    storageBucket: 'ilimi-9f802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jFuruDLWCvBNoxp2BRGmD-fbHc-G1NU',
    appId: '1:167014119386:ios:b66026c0950958cdfb72e3',
    messagingSenderId: '167014119386',
    projectId: 'ilimi-9f802',
    storageBucket: 'ilimi-9f802.firebasestorage.app',
    iosBundleId: 'com.example.ilimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jFuruDLWCvBNoxp2BRGmD-fbHc-G1NU',
    appId: '1:167014119386:ios:b66026c0950958cdfb72e3',
    messagingSenderId: '167014119386',
    projectId: 'ilimi-9f802',
    storageBucket: 'ilimi-9f802.firebasestorage.app',
    iosBundleId: 'com.example.ilimi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN96Sb18FoF7MjSLNZ2tF3yJeIt-7SS7s',
    appId: '1:167014119386:web:14b7762e170d0257fb72e3',
    messagingSenderId: '167014119386',
    projectId: 'ilimi-9f802',
    authDomain: 'ilimi-9f802.firebaseapp.com',
    storageBucket: 'ilimi-9f802.firebasestorage.app',
  );
}
